import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Uili Print v2",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col gap-[1rem] ${inter.className} dark`}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
